// Generated by the asset compression pass: pixel size of looping clips converted from GIF,
// so their box keeps its shape before the video loads.
export const MEDIA_SIZES: Record<string, [number, number]> = {
  "/works/North_Keyboard/gif1.mp4": [
    450,
    800
  ],
  "/works/Octopus/09345c204061893.66a24feeb86e1.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/20518f204061893.66a24feebe41a.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/2a51b2204061893.66a24feeb9fa9.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/2f6196204061893.66a24feebc86d.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/487c2c204061893.66a24feebeba5.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/547947204061893.66a24feebfd57.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/6c3c10204061893.66a24feec07a6.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/76c0f4204061893.66a24feebd092.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/98c260204061893.66a24feeb9a62.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/990381204061893.66a24feebf40b.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/e42db6204061893.66a24feec0f75.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/ebefc1204061893.66a24feec185f.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/eccbd3204061893.66a24feebda5d.mp4": [
    1400,
    1400
  ],
  "/works/Octopus/ed5814204061893.66a24feeb8cab.mp4": [
    1400,
    1400
  ]
};
